version: "2"

services:
  linux:
    build: ./docker-devel/.
    image: linux
    depends_on:
      - phpmyadmin
    ports:
      - "80:80"
    volumes: 
      - "/skateboard:/skateboard"
    links:
      - mysql
      - phpmyadmin
    restart: always

  mysql:
    image: mysql:5.6.26
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tw
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=skateboard
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    volumes:
      - /sessions
    ports:
      - 85:80
    environment:
#      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=test
      - PMA_HOST=mysql
    depends_on:
      - mysql
