version: "2"

services:
  linux:
    build: ./docker/.
    image: linux
    depends_on:
      - phpmyadmin
    ports:
      - "80:80"
    volumes: 
      - "./sync:/test/src"
    links:
      - mysql
      - phpmyadmin
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=dbdatabase
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    volumes:
      - /sessions
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=test123
    depends_on:
      - mysql
