# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/Vagrantfile.config.yaml")
vagrant_config = configs['configs'][configs['configs']['use']]
vagrant_ip = vagrant_config['vagrant_ip'];

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.synced_folder "./..", "/skateboard/src", type: "rsync", rsync__exclude: [".git","devops/.vagrant", "devops/.docker", "configuration","logs", "files", "temp"]
  config.vm.network "private_network", ip: vagrant_ip
  
  config.vm.provider "virtualbox" do |v|
    v.memory  = 2048
  end 
  
  config.vm.provision "docker"
  
  config.vm.provision "docker_compose"
  
  config.vm.provision "shell" do |s|
    s.inline = "echo \"export VAGRANT_IP=$1\" >> /etc/profile"
    s.args   = [vagrant_ip]
  end
  
  config.vm.provision "shell" do |s|
    s.inline = "mkdir /skateboard/database; mkdir /skateboard/log;"
  end
  
  config.vm.provision "shell" do |s|
    s.inline = "ln -s /vagrant /skateboard/src"
  end

  config.vm.provision "shell" do |s|
    s.inline = "rm -rf /skateboard/src/configuration"
  end

  config.vm.provision "shell" do |s|
    s.inline = "ln -s /skateboard/src/devops/config/devel /skateboard/src/configuration"
  end

  config.vm.provision "shell" do |s|
    s.inline = "chown vagrant:vagrant /skateboard"
  end

  config.vm.provision "docker_compose", yml: "/skateboard/src/devops/docker-compose.devel.yml", run: "always"

  config.ssh.insert_key = true
end