#!/bin/bash

############################################################
#### Execute this script only during first installation ####
############################################################

RED='\033[0;31m' # red color
NC='\033[0m' # no color
GREEN='\033[0;32m' # green color
BLUE='\033[0;34m' # blue color
YELLOW='\033[0;33m' # yellow color

echo -e "${GREEN}Executing first boot...${NC}"
echo -e "adfadf"
sleep 1
if [ $# -eq 0 ]
  then
    echo -e "${RED}No arguments supplied -> test environment${NC}"
fi
# to install each command needs word "true" before e.g. "true apt-get update -y"
declare -a commandsToExecute=(
  #update & upgrade
  "apt-get update -y" 
  "apt-get upgrade -y"
  "apt-get dist-upgrade -y"
  # install packages
  "true apt-get install -y git"
  "apt-get install -y build-essential"
  "apt-get install -y python"
  "apt-get install -y python-dev"
  "apt-get install -y python-pip"
  "apt-get install -y python-virtualenv"
  )
for (( i=0; i<${#commandsToExecute[@]}; i++ )); do
  if  [[ ${commandsToExecute[$i]} == true* ]] ; then
    echo -e "executing: ${GREEN}${commandsToExecute[$i]#* }${NC}"
    eval ${commandsToExecute[$i]#* }
  fi
done

pidfile="./info.pid"

#if [ -f "$pidfile" ]; then
  echo -e "${RED}Script was allready executed${YELLOW} (if not delete info.pid)${NC}"
#else
  now=$(date +"%Y-%m-%d %H:%M:%S")


  
  # clean after
  #apt-get clean
  # in case of emergency clean manually 
  #rm -rf /var/lib/apt/lists/*

  #other steps
  #pip install pyserial
  #git clone git://git.drogon.net/wiringPi

  #echo "Executing script for the first time"
  #echo "Current time : $now"
  #echo "Script first_boot was executed successfully: $now" >> $pidfile
#fi   
